deployment:
  tasks:
    - export DEPLOYPATH=/home/kylep910/pandoraportal.ca
    - /bin/mkdir -p $DEPLOYPATH/CSS
    - /bin/mkdir -p $DEPLOYPATH/scripts
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/mkdir -p $DEPLOYPATH/gallery
    - /bin/mkdir -p $DEPLOYPATH/galleryPages
    - /bin/mkdir -p $DEPLOYPATH/font
    - /bin/mkdir -p $DEPLOYPATH/bot_php
    - /bin/mkdir -p $DEPLOYPATH/image_display
    - /bin/mkdir -p $DEPLOYPATH/botimages
    - /bin/cp -R CSS/* $DEPLOYPATH/CSS/
    - /bin/cp -R scripts/* $DEPLOYPATH/scripts/
    - /bin/cp -R images/* $DEPLOYPATH/images/
    - /bin/cp -R gallery/* $DEPLOYPATH/gallery/
    - /bin/cp -R galleryPages/* $DEPLOYPATH/galleryPages/
    - /bin/cp -R font/* $DEPLOYPATH/font/
    - /bin/cp -R bot_php/* $DEPLOYPATH/bot_php/
    - /bin/cp -R image_display/* $DEPLOYPATH/image_display/
    - /bin/cp -R *.php $DEPLOYPATH/
    - /bin/cp -R *.html $DEPLOYPATH/
    - /bin/cp -R .cpanel.yml $DEPLOYPATH/