deployment:
  tasks:
    # Debugging: Print current directory structure
    - echo "DEBUG: Listing botimages/NonGear_Icon..."
    - /bin/ls -la botimages/NonGear_Icon/

    # Debugging: Verify Trove files exist in Git
    - echo "DEBUG: Checking Trove files..."
    - /bin/ls -la botimages/NonGear_Icon/Trove/ || echo "ERROR: Trove folder missing!"

    # Debugging: Test folder creation
    - echo "DEBUG: Creating NonGear_Icon/Trove..."
    - /bin/mkdir -pv $DEPLOYPATH/botimages/NonGear_Icon/Trove

    # Debugging: Test copy command
    - echo "DEBUG: Copying Trove files..."
    - /bin/cp -Rv botimages/NonGear_Icon/Trove/ $DEPLOYPATH/botimages/NonGear_Icon/ || echo "ERROR: Copy failed!"
    - export DEPLOYPATH=/home/kylep910/pandoraportal.ca
    - /bin/mkdir -p $DEPLOYPATH/CSS
    - /bin/mkdir -p $DEPLOYPATH/scripts
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/mkdir -p $DEPLOYPATH/gallery
    - /bin/mkdir -p $DEPLOYPATH/galleryPages
    - /bin/mkdir -p $DEPLOYPATH/font
    - /bin/mkdir -p $DEPLOYPATH/bot_php
    - /bin/mkdir -p $DEPLOYPATH/image_display
    - /bin/mkdir -p $DEPLOYPATH/botimages
    - /bin/mkdir -p $DEPLOYPATH/botimages/NonGear_Icon
    - /bin/cp -R botimages/NonGear_Icon/ $DEPLOYPATH/botimages/
    - /bin/cc -R CSS/* $DEPLOYPATH/CSS/
    - /bin/cp -R scripts/* $DEPLOYPATH/scripts/
    - /bin/cp -R images/* $DEPLOYPATH/images/
    - /bin/cp -R gallery/* $DEPLOYPATH/gallery/
    - /bin/cp -R galleryPages/* $DEPLOYPATH/galleryPages/
    - /bin/cp -R font/* $DEPLOYPATH/font/
    - /bin/cp -R bot_php/* $DEPLOYPATH/bot_php/
    - /bin/cp -R image_display/* $DEPLOYPATH/image_display/
    - /bin/cp -R *.php $DEPLOYPATH/
    - /bin/cp -R *.html $DEPLOYPATH/
    - /bin/cp -R .cpanel.yml $DEPLOYPATH/